from crewai import Task
from agents import researcher_agent, intel_agent, closer_agent

researcher_task = Task(
    description=(
        "Visit and thoroughly analyze the following website: {website_url}. "
        "Your objective is to extract actionable business intelligence. Specifically, you must: "
        "1. Identify their core value proposition. "
        "2. List their main products or services. "
        "3. Define their Ideal Customer Profile (ICP) - who are they selling to? "
        "4. Explicitly uncover the primary pain points and problems their offerings aim to solve."
    ),
    expected_output=(
        "A detailed, structured research report divided into 4 sections: "
        "1) Company Overview & Value Proposition, "
        "2) Key Products/Services, "
        "3) Ideal Customer Profile (ICP), "
        "4) Core Pain Points Addressed."
    ),
    agent=researcher_agent
)

intel_task = Task(
    description=(
        "Review the research report generated by the Researcher for the company at {website_url}. "
        "Your goal is to synthesize this data and formulate a highly compelling 'Sales Angle' or 'Hook' for our outreach. "
        "Identify specific vulnerabilities, gaps in their current messaging, or unaddressed problems of their target audience "
        "where our solution ({our_solution}) can seamlessly fit in and provide immense value."
    ),
    expected_output=(
        "A strategic intelligence brief containing: "
        "1) The Chosen Sales Angle/Hook, "
        "2) The Strategic Rationale (Why this angle will resonate based on their specific pain points), "
        "3) A 'Vulnerability/Gap' analysis highlighting what they are currently missing."
    ),
    agent=intel_agent
)

closer_task = Task(
    description=(
        "Using the strategic intelligence brief provided by the Intel Agent, write a concise, highly personalized B2B cold email "
        "addressed to a key decision-maker at the target company ({website_url}). "
        "The email must leverage the suggested 'Sales Angle' to instantly capture attention in the first sentence. "
        "Clearly articulate how our solution ({our_solution}) addresses their specific pain point, and end with a soft, low-friction Call to Action (CTA). "
        "Crucial: The tone must be professional, direct, and advisory—absolutely no sleazy sales language."
    ),
    expected_output=(
        "A final, ready-to-send B2B cold email that includes: "
        "- An engaging, non-clickbaity Subject Line. "
        "- A highly personalized opening line based on their company data. "
        "- A clear, concise value proposition directly tied to their identified pain points. "
        "- A single, clear, and low-friction Call to Action (CTA). "
        "The total email length must be under 150 words."
    ),
    agent=closer_agent
)
